export const INCREMENT_BACKGROUND_COUNTER = 'INCREMENT_BACKGROUND_COUNTER';
export const DECREMENT_BACKGROUND_COUNTER = 'DECREMENT_BACKGROUND_COUNTER';
export const INCREMENT_UI_COUNTER = 'INCREMENT_UI_COUNTER';
export const DECREMENT_UI_COUNTER = 'DECREMENT_UI_COUNTER';
